spring.application.name=Backend

gemini.api.key=AIzaSyC3DhUwnteL3qM-kAPnK7o1_v6UUrPyb2I

logging.level.com.project.Backend=DEBUG
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:testdb
spring.jpa.defer-datasource-initialization=true

