spring.application.name=Backend

gemini.api.key=AIzaSyC3DhUwnteL3qM-kAPnK7o1_v6UUrPyb2I

logging.level.com.project.Backend=DEBUG
spring.datasource.url=jdbc:mysql://localhost:3306/bus_tracker?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Bhaktii@2005
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql

