INSERT INTO BUS_LOCATION (BUS_ID, ROUTE_NAME, LAT, LNG, SPEED_KMH, TIMESTAMP)
VALUES ('BUS-101', 'Route A', 15.8152, 74.4871, 30, CURRENT_TIMESTAMP)
ON DUPLICATE KEY UPDATE ROUTE_ID='ROUTE_A', LAT=15.8152, LNG=74.4871, ROUTE_NAME='Route A';

INSERT INTO BUS_LOCATION (BUS_ID, ROUTE_NAME, LAT, LNG, SPEED_KMH, TIMESTAMP)
VALUES ('BUS-202', 'Route B', 15.8152, 74.4871, 25, CURRENT_TIMESTAMP)
ON DUPLICATE KEY UPDATE ROUTE_ID='ROUTE_B', LAT=15.8152, LNG=74.4871, ROUTE_NAME='Route B';

INSERT INTO BUS_LOCATION (BUS_ID, ROUTE_NAME, LAT, LNG, SPEED_KMH, TIMESTAMP)
VALUES ('BUS-303', 'Route C', 12.9900, 77.6100, 40, CURRENT_TIMESTAMP)
ON DUPLICATE KEY UPDATE ROUTE_ID='ROUTE_C';

-- Clear existing dummy route stops for Route A & B to prevent duplicate rows on restart
DELETE FROM ROUTE_STOP WHERE ROUTE_ID='ROUTE_A';
DELETE FROM ROUTE_STOP WHERE ROUTE_ID='ROUTE_B';

-- ROUTE A
INSERT INTO ROUTE_STOP (ROUTE_ID, STOP_ORDER, STOP_NAME, LAT, LNG)
VALUES ('ROUTE_A', 1, 'KLS Gogte Institute of Technology', 15.8152, 74.4871);

INSERT INTO ROUTE_STOP (ROUTE_ID, STOP_ORDER, STOP_NAME, LAT, LNG)
VALUES ('ROUTE_A', 2, 'McDonald''s', 15.8211, 74.4940);

INSERT INTO ROUTE_STOP (ROUTE_ID, STOP_ORDER, STOP_NAME, LAT, LNG)
VALUES ('ROUTE_A', 3, 'Khau Khatta', 15.8420, 74.5083);

INSERT INTO ROUTE_STOP (ROUTE_ID, STOP_ORDER, STOP_NAME, LAT, LNG)
VALUES ('ROUTE_A', 4, 'INOX Cinema', 15.8532, 74.5094);

-- ROUTE B
INSERT INTO ROUTE_STOP (ROUTE_ID, STOP_ORDER, STOP_NAME, LAT, LNG)
VALUES ('ROUTE_B', 1, 'KLS Gogte Institute of Technology', 15.8152, 74.4871);

INSERT INTO ROUTE_STOP (ROUTE_ID, STOP_ORDER, STOP_NAME, LAT, LNG)
VALUES ('ROUTE_B', 2, 'RPD', 15.8330, 74.5122);

INSERT INTO ROUTE_STOP (ROUTE_ID, STOP_ORDER, STOP_NAME, LAT, LNG)
VALUES ('ROUTE_B', 3, 'Goaves', 15.8406, 74.5088);

INSERT INTO ROUTE_STOP (ROUTE_ID, STOP_ORDER, STOP_NAME, LAT, LNG)
VALUES ('ROUTE_B', 4, 'Swaroop nartaki', 15.8510, 74.5152);

INSERT INTO DRIVER_USER (DRIVER_ID, NAME, USERNAME, PASSWORD, ASSIGNED_BUS_ID)
VALUES ('DRV-101', 'Ramesh Kumar', 'driver101', 'driver123', 'BUS-101')
ON DUPLICATE KEY UPDATE NAME='Ramesh Kumar';

INSERT INTO DRIVER_USER (DRIVER_ID, NAME, USERNAME, PASSWORD, ASSIGNED_BUS_ID)
VALUES ('DRV-202', 'Suresh Rao', 'driver202', 'driver123', 'BUS-202')
ON DUPLICATE KEY UPDATE NAME='Suresh Rao';