INSERT INTO BUS_LOCATION (BUS_ID, ROUTE_NAME, LAT, LNG, SPEED_KMH, TIMESTAMP)
VALUES ('BUS-101', 'Route A', 15.8152, 74.4871, 30, CURRENT_TIMESTAMP);
INSERT INTO BUS_LOCATION (BUS_ID, ROUTE_NAME, LAT, LNG, SPEED_KMH, TIMESTAMP)
VALUES ('BUS-202', 'Route B', 12.9352, 77.6245, 25, CURRENT_TIMESTAMP);
INSERT INTO BUS_LOCATION (BUS_ID, ROUTE_NAME, LAT, LNG, SPEED_KMH, TIMESTAMP)
VALUES ('BUS-303', 'Route C', 12.9900, 77.6100, 40, CURRENT_TIMESTAMP);

UPDATE BUS_LOCATION SET ROUTE_ID='ROUTE_A' WHERE BUS_ID='BUS-101';
UPDATE BUS_LOCATION SET ROUTE_ID='ROUTE_B' WHERE BUS_ID='BUS-202';
UPDATE BUS_LOCATION SET ROUTE_ID='ROUTE_C' WHERE BUS_ID='BUS-303';

INSERT INTO ROUTE_STOP (ROUTE_ID, STOP_ORDER, STOP_NAME, LAT, LNG)
VALUES ('ROUTE_A', 1, 'KLS Gogte Institute of Technology', 15.8152, 74.4871);

INSERT INTO ROUTE_STOP (ROUTE_ID, STOP_ORDER, STOP_NAME, LAT, LNG)
VALUES ('ROUTE_A', 2, 'McDonald_s', 15.8211, 74.4940);

INSERT INTO ROUTE_STOP (ROUTE_ID, STOP_ORDER, STOP_NAME, LAT, LNG)
VALUES ('ROUTE_A', 3, 'Khau Khatta', 15.8420, 74.5083);

INSERT INTO ROUTE_STOP (ROUTE_ID, STOP_ORDER, STOP_NAME, LAT, LNG)
VALUES ('ROUTE_A', 4, 'INOX Cinema', 15.8532, 74.5094);

INSERT INTO DRIVER_USER (DRIVER_ID, NAME, USERNAME, PASSWORD, ASSIGNED_BUS_ID)
VALUES ('DRV-101', 'Ramesh Kumar', 'driver101', 'driver123', 'BUS-101');
INSERT INTO DRIVER_USER (DRIVER_ID, NAME, USERNAME, PASSWORD, ASSIGNED_BUS_ID)
VALUES ('DRV-202', 'Suresh Rao', 'driver202', 'driver123', 'BUS-202');